name: pr

on:
  push:
    branches:
      - pull-request

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - run: echo "building and testing the app ..."
  docker-build-push:
    runs-on: ubuntu-latest
    needs: build-test
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          file: Dockerfile
          push: true
          tags: kingbj0429/github-action-kotlin:${{ github.sha }}
  update-image-tag-in-helm:
    runs-on: ubuntu-latest
    needs: docker-build-push
    steps:
      - run: |
          git config --global user.email kingbj0429@gmail.com && git config --global user.name kingbj940429
          echo "cloning app repo"
          git clone -b feature/github-action-kotlin https://oauth2:${{ secrets.GH_PAT }}@github.com/${{ github.repository_owner }}/csg-sd-helm-charts.git
          cd ./csg-sd-helm-charts/platform/dev/sample/github-action-kotlin
          echo "checkout source branch"
          git checkout feature/github-action-kotlin
          echo "updating image tag in values file"
          sed -i "s,tag:.*,tag:\ ${{ github.sha }}," ./values.yaml
          git add . && git commit -m "update image tag"
          git push