name: 'test-every-push'

on: push
jobs:
  test:
    name: Test lint, src, build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: ${{ secrets.JAVA_VERSION }}
          cache: 'gradle'
      - run: ./gradlew build --no-daemon

      - run: |
          echo "Hello!!"
